---

- name: Restart application
  supervisorctl: name={{ application_name }} state=restarted
  notify: Turn off maintenance
  tags: 
    - deploy

- name: Turn off maintenance
  command: mv {{ virtualenv_path }}/maintenance_on.html {{ virtualenv_path }}/maintenance_off.html
  tags: 
    - deploy

- name: Restart nginx
  service: name=nginx state=restarted enabled=yes
