---

- name: Check if first config or a regular deploy
  stat: path={{ virtualenv_path }}/maintenance_off.html
  register: maintenance_stat
  tags: 
    - deploy

- name: Turn on maintenance before deploy
  command: mv {{ virtualenv_path }}/maintenance_off.html {{ virtualenv_path }}/maintenance_on.html
  when: maintenance_stat.stat.exists
  tags: 
    - deploy

- name: Make sure app is stopped before deply
  supervisorctl: name={{ application_name }} state=stopped
  tags: 
    - deploy
